[package]
edition = "2021"
name = "mips-sim"
version = "0.1.0"

[dependencies]

anyhow = { workspace = true }
bitmatch = { workspace = true }
clap = { workspace = true, features = ["derive"] }
clap-num = { workspace = true }
ddw3-logger = { workspace = true }
tracing = { workspace = true }
