[build]
dep-info-basedir = ".."
target = "mipsel-sony-psx"
rustflags = [
	"-Crelocation-model=static",
	"-Cdefault-linker-libraries=no",
	"-Ztrap-unreachable=no",
]

[target."mipsel-sony-psx"]
linker = "mips-elf-ld"

[unstable]
build-std = ["core"]
