[package]
edition = "2021"
name = "dw2003_pro_sdigiedt"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]

panic_handler = { workspace = true }
types = { workspace = true }
util = { workspace = true }
