entries = [
	"0/0.bin",
	"0/1.bin",
	"0/2.bin",
	"0/3.bin",
	"0/4.bin",
	"0/5.bin",
	"0/6.bin",
	"0/7.bin",
	"0/8.bin",
	"0/9.bin",
	"0/10.bin",
	"0/11.bin",
	"0/12.bin",
	"0/13.bin",
	"0/14.bin",
	"0/15.bin",
	"0/16.bin",
	"0/17.bin",
	"0/18.bin",
	"0/19.bin",
	"0/20.bin",
	"0/21.bin",
	"0/22.bin",
	"0/23.bin",
	"0/24.bin",
	"0/25.bin",
	"0/26.bin",
	"0/27.bin",
	"0/28.bin",
	"0/29.bin",
	"0/30.bin",
	"0/31.bin",
	"0/32.bin",
	"0/33.bin",
	"0/34.bin",
	"0/35.bin",
	"0/36.bin",
	"0/37.bin",
	"0/38.bin",
	"0/39.bin",
	"0/40.bin",
	"0/41.bin",
	"0/42.bin",
	"0/43.bin",
	"0/44.bin",
	"0/45.bin",
	"0/46.bin",
	"0/47.bin",
	"0/48.bin",
	"0/49.bin",
	"0/50.bin",
	"0/51.bin",
	"0/52.bin",
	"0/53.bin",
	"0/54.bin",
	"0/55.bin",
	"0/56.bin",
	"0/57.bin",
	"0/58.bin",
	"0/59.bin",
	"0/60.bin",
	"0/61.bin",
	"0/62.bin",
	"0/63.bin",
	"0/64.bin",
	"0/65.bin",
	"0/66.bin",
	"0/67.bin",
	"0/68.bin",
	"0/69.bin",
	"0/70.bin",
	"0/71.bin",
	"0/72.bin",
	"0/73.bin",
	"0/74.bin",
	"0/75.bin",
	"0/76.bin",
	"0/77.bin",
	"0/78.bin",
	"0/79.bin",
	"0/80.bin",
	"0/81.bin",
	"0/82.bin",
	"0/83.bin",
	"0/84.bin",
	"0/85.bin",
	"0/86.bin",
	"0/87.bin",
	"0/88.bin",
	"0/89.bin",
	"0/90.bin",
	"0/91.bin",
	"0/92.bin",
	"0/93.bin",
	"0/94.bin",
	"0/95.bin",
]
