start_addr = 0x80010000
objs = [
	"/build/asm/dw2003/exe/start.o",
	"/build/asm/dw2003/exe/fns.o",
	"/build/asm/dw2003/exe/f0.o",
	"/build/asm/dw2003/exe/f1.o",
	"/build/asm/dw2003/exe/f2.o",
	"/build/asm/dw2003/exe/f3.o",
	"/build/asm/dw2003/exe/f4.o",
	"/build/asm/dw2003/exe/f5.o",
	"/build/asm/dw2003/exe/f6.o",
	"/build/asm/dw2003/exe/f7.o",
	"/build/asm/dw2003/exe/f8.o",
	"/build/asm/dw2003/exe/f9.o",
	"/build/asm/dw2003/exe/f10.o",
	"/build/asm/dw2003/exe/f11.o",
	"/build/asm/dw2003/exe/f12.o",
	"/build/asm/dw2003/exe/f13.o",
	"/build/asm/dw2003/exe/f14.o",
	"/build/asm/dw2003/exe/f15.o",
	"/build/asm/dw2003/exe/f16.o",
	"/build/asm/dw2003/exe/loading.o",
	"/build/rust/dw2003_exe.a",
]
sections = [
	"fns0_0",
	"section_start",
	"section_f13",
	"fns0_1",
	"section_f2",
	"section_f1",
	"section_f0",
	"section_f4",
	"section_f5",
	"section_f6",
	"section_f7",
	"section_f3",
	"section_f8",
	"section_f9",
	"fns1_0",
	"section_f12",
	"fns1_1",
	"section_f10",
	"fns2",
	"section_f11",
	"fns3_00",
	"section_f15",
	"fns3_010",
	"section_f16",
	"fns3_011",
	"section_f14",
	"fns3_1",
	"dw2003_exe_data0",
	"dw2003_exe_digimon_profiles",
	"dw2003_exe_data1",
	"loading_img",
]
