start_addr = 0x80000000 # TODO: Placeholder, replace
objs = [
	"/build/asm/dw2003/pro/fieldstg.o",
	"/build/rust/dw2003_pro_fieldstg_data.o",
]
sections = ["section_FIELDSTG", "dw2003_pro_FIELDSTG_data"]
