start_addr = 0x80082cb0
objs = [
	"/build/asm/dw2003/pro/stfgtrep.o",
	"/build/asm/dw2003/pro/stfgtrep/f0.o",
	"/build/rust/dw2003_pro_stfgtrep_data.o",
]
sections = [
	"section_STFGTREP_0",
	"section_STFGTREP_f0",
	"section_STFGTREP_1",
	"dw2003_pro_STFGTREP_data",
]
