start_addr = 0x80000000 # TODO: Placeholder, replace
objs = [
	"/build/asm/dw2003/pro/stgtrain.o",
	"/build/asm/dw2003/pro/stgtrain/f0.o",
	"/build/asm/dw2003/pro/stgtrain/f1.o",
	"/build/asm/dw2003/pro/stgtrain/f9.o",
	"/build/asm/dw2003/pro/stgtrain/f10.o",
	"/build/asm/dw2003/pro/stgtrain/f11.o",
	"/build/rust/dw2003_pro_stgtrain_data.a",
]
sections = [
	"section_STGTRAIN_0",
	"section_STGTRAIN_f0",
	"section_STGTRAIN_f1",
	"section_STGTRAIN_f2",
	"section_STGTRAIN_f3",
	"section_STGTRAIN_f4",
	"section_STGTRAIN_f5",
	"section_STGTRAIN_f6",
	"section_STGTRAIN_f7",
	"section_STGTRAIN_f8",
	"section_STGTRAIN_f9",
	"section_STGTRAIN_f10",
	"section_STGTRAIN_f11",
	"section_STGTRAIN_1",
	"dw2003_pro_STGTRAIN_data",
]
